### ISSUE TITLE
what is profile???

### ISSUE THREAD

**Issue by sweetyRay** [youknow0/pfsense-vouchergen#1]
in the code there is profile ?? what it is ?? 
thanx you

**Comment by youknow0** [comment]
See [config.example.php](https://github.com/youknow0/pfsense-vouchergen/blob/46efcdae665f4e7dc7c13a54f568c03139ce307d/voucher_gen/config.example.php). The web interface provides a drop down menu where users may select one of several profiles. The profile determines the number of vouchers being generated and their validity. 

Important: this code is no longer maintained. I don’t know if it still works with current pfSense versions.
